services:

  db:
    image: postgis/postgis:15-3.3
    container_name: smartbike_db
    environment:
      POSTGRES_USER: smartbike
      POSTGRES_PASSWORD: smartbike123
      POSTGRES_DB: smartbike_vilareal2
    ports:
      - "5432:5432"
    volumes:
      - smartbike_db_data:/var/lib/postgresql/data
      - ./backend/sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartbike -d smartbike_vilareal2"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: smartbike_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: smartbike_vilareal2
      DB_USER: smartbike
      DB_PASSWORD: smartbike123
    volumes:
      - ./backend:/app

volumes:
  smartbike_db_data:
